#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/manage.py syncdb --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/manage.py syncdb --noinput
python "$OPENSHIFT_REPO_DIR".openshift/action_hooks/secure_db.py | tee -a ${OPENSHIFT_DATA_DIR}/CREDENTIALS

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/manage.py collectstatic --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/manage.py collectstatic --noinput > /dev/null

echo "Executing 'chmod +x $OPENSHIFT_REPO_DIR/.openshift/cron/daily/dbbackup.sh'"
chmod +x "$OPENSHIFT_REPO_DIR".openshift/cron/daily/dbbackup.sh
